### ISSUE TITLE
Listings amount discrepancy

### ISSUE THREAD

**Issue by cherouvim** [EuropeanUniversityFoundation/home_api_middleware#11]
Please see this screenshot:

![image](https://github.com/EuropeanUniversityFoundation/home_api_middleware/assets/743305/958dd245-3374-4531-be04-dc46750d12ea)

There are 4 items in the `listings` array, but the `pagination.totalListings` says 5. This causes an issue on our "load more" functionality. I assume this has happened because the duplicates (a bug discovered earlier) has been fixed on the middleware (filtering things out?) but not on the actual datasource. In any case, the pagination listings number should reflect the actual number.

**Comment by ittisvagyok** [comment]
I have created a fix for this issue. It's currently on branch [1.2.0-dev](https://github.com/EuropeanUniversityFoundation/home_api_middleware/tree/1.2.0-dev). 

@cherouvim Did you create a fix for this on the frontend? Should I tag a release?

**Comment by cherouvim** [comment]
Hello. We did not fix this ourselves on our frontend. I used `1.2.0-dev` and the issue seems solved, so feel free to tag.

Thanks!
